### ISSUE TITLE
Latest version does not work with ubuntu 24.04

### ISSUE THREAD

**Issue by cccs-gjhouns** [microsoft/vsts-azurevm-extension#241]
When running the latest version with the supposed fix, the following error is given:

`The handler for VM extension type 'Microsoft.VisualStudio.Services.TeamServicesAgentLinux' has reported terminal failure for VM extension 'Microsoft.Azure.DevOps.Pipelines.Agent' with error message: '[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/Handler.sh [stdout] [stderr] Traceback (most recent call last):   File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/Utils/WAAgentUtil.py", line 57, in <module>     waagent = imp.load_source('waagent', agentPath)               ^^^^^^^^^^^^^^^ AttributeError: module 'importlib' has no attribute 'load_source' During handling of the above exception, another exception occurred: Traceback (most recent call last):   File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/./AzureRM.py", line 9, in <module>     import Utils.HandlerUtil as Util   File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/Utils/HandlerUtil.py", line 71, in <module>     from .WAAgentUtil import waagent   File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/Utils/WAAgentUtil.py", line 64, in <module>     waagent = imp.load_source('waagent', agentPath)               ^^^^^^^^^^^^^^^ AttributeError: module 'importlib' has no attribute 'load_source' '.      'Install handler failed for the extension. More information on troubleshooting is available at
[https://aka.ms/vmextensionlinuxtroubleshoot'](https://aka.ms/vmextensionlinuxtroubleshoot%27)`

Of note is `WAAgentUtil.py` imports `importlib` as `imp` but then attemps to call `load_source` which does not exist on `importlib`

**Comment by tkasparek** [comment]
Should be fixed with 1.26.2.0 which is currently being rolled out. Please reopen if you see the issues with 1.26.2.0 or higher.

**Comment by gavintoddchurch** [comment]
@tkasparek that extension is getting reverted back to 1.23 after updating to 1.26.x

Any ideas on why that would be?

**Comment by Adrii77** [comment]
@gavintoddchurch Are you still facing this rollback ? If yes, do you find any solution ?

**Comment by mario-d-s** [comment]
@gavintoddchurch I was still seeing this last week, but today we recreated the VMSS and the agent pool in Azure DevOps and it installed the latest (1.26) version of the extension on the VMSS immediately.

I don't know whether it is only fixed for creating new VMSS/agent pool or whether the team managed to resolve the issue for everyone...

**Comment by gavintoddchurch** [comment]
@Adrii77 @mario-d-s 
I've been testing this every couple of days and seeing the same results, It updates and then reverts back. I opened up a support ticket with Azure. Yesterday evening I tested it again and it has not reverted back and I just got an email as I was writing this informing me that the have applied a fix and it shouldn't revert back now. It has now been like 15 hours or so without the revert back so i'm optimistic that this has been fixed.

**Comment by Adrii77** [comment]
@mario-d-s @gavintoddchurch 
Thank you for taking the time to respond to me :) !
We'll try to recreate the VMSS from scratch. This is something that we haven't tested yet, as we use IaC with Terraform (and VMSS is not really destroy, but updated).

**Comment by tkasparek** [comment]
Reverting back to 1.23 should get fixed today.

**Comment by gavintoddchurch** [comment]
It has been over a week for me without any revert. I've closed my MS ticket now that it has been a week as well.
